-- MySQL Script generated by MySQL Workbench
-- Tue Dec 14 12:19:21 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Restuarnts_ER_Tables
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Restuarnts_ER_Tables
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Restuarnts_ER_Tables` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `Restuarnts_ER_Tables` ;

-- -----------------------------------------------------
-- Table `Restuarnts_ER_Tables`.`UserProfileData`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restuarnts_ER_Tables`.`UserProfileData` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(40) NULL,
  `FirstName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Gender` VARCHAR(6) NULL,
  `Address` VARCHAR(50) NULL,
  `PhoneNumber` VARCHAR(12) NOT NULL,
  `Email` VARCHAR(100) NULL,
  `UserProfilePictures` VARCHAR(140) NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  UNIQUE INDEX `UserName_UNIQUE` (`UserName` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restuarnts_ER_Tables`.`RestaurantDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restuarnts_ER_Tables`.`RestaurantDetails` (
  `RestaurantID` INT NOT NULL AUTO_INCREMENT,
  `RestaurantTitle` VARCHAR(100) NULL,
  `Ratings` FLOAT NULL,
  `RestaurantImage` VARCHAR(255) NOT NULL,
  `RestaurantDescription` TEXT(1024) NULL,
  `Hyperlink_of_Restaurant` VARCHAR(255) NOT NULL,
  `EthnicRestaurant` VARCHAR(45) NULL,
  `RestaurantAddress` VARCHAR(100) NULL,
  `OpeningHourRestaurant` VARCHAR(40) NULL,
  `RestaurantFoodPictures` VARCHAR(45) NOT NULL,
  `RestaurantFoodDiscription` TEXT(1024) NULL,
  `RestaurantFoodPrice` DECIMAL(3,2) NULL,
  PRIMARY KEY (`RestaurantID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restuarnts_ER_Tables`.`ReviewRestaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restuarnts_ER_Tables`.`ReviewRestaurant` (
  `ReviewUserID` INT NOT NULL AUTO_INCREMENT,
  `ReviewResturantsID` INT NOT NULL,
  `ReviewTitle` VARCHAR(70) NULL,
  `ReviewRestaurantName` VARCHAR(60) NULL,
  `Ratings` FLOAT NULL,
  `RatingPrice` FLOAT NOT NULL,
  `RatingFood` FLOAT NOT NULL,
  `RatingService` FLOAT NOT NULL,
  `ReviewComment` TEXT(1024) NULL,
  `ReviewPhoto` VARCHAR(255) NOT NULL,
  `ReviewRestuarntHyperLink` VARCHAR(150) NOT NULL,
  `ReviewByUserName` VARCHAR(100) NULL,
  `DatePost` DATETIME NULL,
  PRIMARY KEY (`ReviewUserID`),
  INDEX `RestaurantOwnReviw_idx` (`ReviewResturantsID` ASC) VISIBLE,
  CONSTRAINT `UserName`
    FOREIGN KEY (`ReviewUserID`)
    REFERENCES `Restuarnts_ER_Tables`.`UserProfileData` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `RestaurantOwnReviw`
    FOREIGN KEY (`ReviewResturantsID`)
    REFERENCES `Restuarnts_ER_Tables`.`RestaurantDetails` (`RestaurantID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
